if(require && exports) {
    var DOM = require('dom');
    var Attr = DOM.Attr;
    var CDATASection = DOM.CDATASection;
    var CharacterData = DOM.CharacterData;
    var Comment = DOM.Comment;
    var Document = DOM.Document;
    var DocumentFragment = DOM.DocumentFragment;
    var DocumentType = DOM.DocumentType;
    var DOMException = DOM.DOMException;
    var DOMImplementation = DOM.DOMImplementation;
    var Element = DOM.Element;
    var Entity = DOM.Entity;
    var EntityReference = DOM.EntityReference;
    var NamedNodeMap = DOM.NamedNodeMap;
    var Namespace = DOM.Namespace;
    var Node = DOM.Node;
    var NodeList = DOM.NodeList;
    var Notation = DOM.Notation;
    var ProcessingInstruction = DOM.ProcessingInstruction;
    var Text = DOM.Text;
    var Range = DOM.Range;
    var XMLSerializer = DOM.XMLSerializer;
    var DOMParser = DOM.DOMParser;
}
